// Generates the C++ bridge header from the bridge registry's JSON Schema.
// Supports exactly the shapes the bridge uses and throws on anything else, so a schema change the
// generator can't represent faithfully fails `npm run schema` instead of drifting silently.
type JsonSchema = {
  type?: string | string[];
  enum?: string[];
  const?: string;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  anyOf?: JsonSchema[];
  oneOf?: JsonSchema[];
  $ref?: string;
  minimum?: number;
  maximum?: number;
  exclusiveMinimum?: number;
  exclusiveMaximum?: number;
  cpp?: string;
  description?: string;
};

// Score IR types are parsed by core (flowstate::parseScore), so the bridge carries them as JSON.
const OPAQUE = new Set(["Score", "ScorePart"]);
const SAFE_INT = 9007199254740991;

type Field = { key: string; cpp: string; nullable: boolean; min?: number; max?: number; integer: boolean };
type Struct = { kind: "struct"; name: string; fields: Field[]; literals: [string, string][]; deps: string[] };
type Enum = { kind: "enum"; name: string; values: string[] };
type Union = { kind: "union"; name: string; members: { name: string; tag: string }[]; discriminator: string };
type Decl = Struct | Enum | Union;

const pascal = (s: string) =>
  s.replace(/#/g, "_sharp").split(/[_\s-]+/).filter(Boolean).map((w) => w[0]!.toUpperCase() + w.slice(1)).join("");
const lowerFirst = (s: string) => s[0]!.toLowerCase() + s.slice(1);
const q = (s: string) => JSON.stringify(s);

function fail(where: string, msg: string): never {
  throw new Error(`cpp-gen: ${where}: ${msg}`);
}

function refName(ref: string): string {
  return ref.replace(/^#\/\$defs\//, "");
}

export function generateCpp(defs: Record<string, JsonSchema>, bridgeId: string): string {
  const decls = new Map<string, Decl>();

  for (const [name, schema] of Object.entries(defs)) {
    if (OPAQUE.has(name)) continue;
    if (schema.enum) {
      decls.set(name, { kind: "enum", name, values: schema.enum });
    } else if (schema.oneOf) {
      decls.set(name, unionDecl(name, schema, defs));
    } else if (schema.type === "object") {
      decls.set(name, structDecl(name, schema));
    } else {
      fail(name, "top-level defs must be enums, objects or discriminated unions");
    }
  }
  for (const d of decls.values())
    if (d.kind === "struct")
      for (const dep of d.deps)
        if (decls.get(dep)?.kind === "union") fail(`${d.name}`, `unions can't be fields (${dep})`);

  const order = topoSort(decls);
  const out: string[] = [];
  const w = (line = "") => out.push(line);

  w("// Generated by schema/src/generate.ts from schema/src/bridge.ts. Do not edit.");
  w("// Semantics: docs/bridge-spec.md.");
  w("#pragma once");
  w();
  for (const h of ["cstdint", "optional", "stdexcept", "string", "string_view", "type_traits", "utility", "variant", "vector"])
    w(`#include <${h}>`);
  w();
  w("#include <nlohmann/json.hpp>");
  w();
  w("namespace flowstate::bridge {");
  w();
  w("using json = nlohmann::json;");
  w();
  w(`inline constexpr const char* kBridgeId = ${q(bridgeId)};`);
  w();
w(PARSE_ERROR);
  w();
  w(DETAIL_PRELUDE);

  // Enums.
  for (const d of order) {
    if (d.kind !== "enum") continue;
    w(`enum class ${d.name} { ${d.values.map(pascal).join(", ")} };`);
  }
  w();
  // Structs.
  for (const d of order) {
    if (d.kind === "struct") {
      if (d.fields.length === 0) {
        w(`struct ${d.name} {};`);
      } else {
        w(`struct ${d.name} {`);
        for (const f of d.fields) w(`    ${f.nullable ? `std::optional<${f.cpp}>` : f.cpp} ${f.key}${defaultInit(f, decls)};`);
        w("};");
      }
      w();
    } else if (d.kind === "union") {
      w(`using ${d.name} = std::variant<${d.members.map((m) => m.name).join(", ")}>;`);
      w();
    }
  }

  // Declarations, so definitions can refer to each other in any order.
  for (const d of order) {
    if (d.kind === "enum") {
      w(`const char* toString(${d.name} value);`);
      w(`std::optional<${d.name}> parse${d.name}(std::string_view text);`);
    }
    if (d.kind === "union") {
      w(`${unionTemplate(d.name)}\nvoid to_json(json& j, const U& value);`);
      w(`${unionTemplate(d.name)}\nvoid from_json(const json& j, U& value);`);
      continue;
    }
    const arg = d.kind === "enum" ? d.name : `const ${d.name}&`;
    w(`void to_json(json& j, ${arg} value);`);
    w(`void from_json(const json& j, ${d.name}& value);`);
  }
  w();

  for (const d of order) {
    if (d.kind === "enum") emitEnum(d, w);
    else if (d.kind === "struct") emitStruct(d, w);
    else emitUnion(d, w);
  }
  w("}  // namespace flowstate::bridge");
  return out.join("\n") + "\n";
}

function defaultInit(f: Field, decls: Map<string, Decl>): string {
  if (f.nullable) return "";
  if (f.cpp === "bool") return " = false";
  if (f.cpp === "double") return ` = ${f.min !== undefined && f.min > 0 ? f.min.toFixed(1) : "0.0"}`;
  if (f.cpp === "int" || f.cpp === "std::int64_t") return ` = ${f.min !== undefined && f.min > 0 ? f.min : 0}`;
  const d = decls.get(f.cpp);
  if (d?.kind === "enum") return ` = ${f.cpp}::${pascal(d.values[0]!)}`;
  return "";
}

function unionDecl(name: string, schema: JsonSchema, defs: Record<string, JsonSchema>): Union {
  const members = schema.oneOf!.map((m) => {
    if (!m.$ref) fail(name, "union members must be named (registered) objects");
    return refName(m.$ref);
  });
  const first = defs[members[0]!]!;
  const discriminator = Object.keys(first.properties ?? {}).find((k) =>
    members.every((m) => defs[m]?.properties?.[k]?.const !== undefined),
  );
  if (!discriminator) fail(name, "no shared const discriminator");
  const tags = members.map((m) => ({ name: m, tag: defs[m]!.properties![discriminator]!.const! }));
  if (new Set(tags.map((t) => t.tag)).size !== tags.length) fail(name, "duplicate discriminator values");
  return { kind: "union", name, members: tags, discriminator };
}

function structDecl(name: string, schema: JsonSchema): Struct {
  const fields: Field[] = [];
  const literals: [string, string][] = [];
  const deps = new Set<string>();
  const required = new Set(schema.required ?? []);
  for (const [key, prop] of Object.entries(schema.properties ?? {})) {
    const where = `${name}.${key}`;
    if (!required.has(key)) fail(where, "optional keys aren't allowed; use nullable");
    if (prop.const !== undefined) {
      literals.push([key, prop.const]);
      continue;
    }
    let inner = prop;
    let nullable = false;
    if (Array.isArray(prop.type)) {
      const nonNull = prop.type.filter((t) => t !== "null");
      if (nonNull.length !== 1 || prop.type.length !== 2) fail(where, "only T | null unions are supported as fields");
      inner = { ...prop, type: nonNull[0]! };
      nullable = true;
    } else if (prop.anyOf) {
      const nonNull = prop.anyOf.filter((s) => s.type !== "null");
      if (nonNull.length !== 1 || prop.anyOf.length !== 2) fail(where, "only T | null unions are supported as fields");
      inner = nonNull[0]!;
      nullable = true;
    }
    fields.push({ key, nullable, ...typeOf(inner, where, deps) });
  }
  return { kind: "struct", name, fields, literals, deps: [...deps] };
}

function typeOf(s: JsonSchema, where: string, deps: Set<string>): Omit<Field, "key" | "nullable"> {
  if (s.$ref) {
    const n = refName(s.$ref);
    if (OPAQUE.has(n)) return { cpp: "json", integer: false };
    deps.add(n);
    return { cpp: n, integer: false };
  }
  if (s.anyOf || s.oneOf || Array.isArray(s.type)) fail(where, "nested unions aren't supported");
  if (s.enum) fail(where, "inline enums aren't supported; register the enum");
  if (s.exclusiveMinimum !== undefined || s.exclusiveMaximum !== undefined) fail(where, "exclusive bounds aren't supported");
  const bounds = {
    ...(s.minimum !== undefined && s.minimum > -SAFE_INT ? { min: s.minimum } : {}),
    ...(s.maximum !== undefined && s.maximum < SAFE_INT ? { max: s.maximum } : {}),
  };
  switch (s.type) {
    case "string":
      return { cpp: "std::string", integer: false };
    case "boolean":
      return { cpp: "bool", integer: false };
    case "number":
      return { cpp: "double", integer: false, ...bounds };
    case "integer": {
      const cpp = s.cpp === "int64" ? "std::int64_t" : "int";
      if (cpp === "int" && ((bounds.max ?? 0) > 2147483647 || (bounds.min ?? 0) < -2147483648))
        fail(where, "bounds exceed int; add .meta({ cpp: \"int64\" })");
      return { cpp, integer: true, ...bounds };
    }
    case "array": {
      if (!s.items) fail(where, "array without items");
      const item = typeOf(s.items, `${where}[]`, deps);
      if (item.min !== undefined || item.max !== undefined) fail(where, "bounds on array items aren't supported");
      return { cpp: `std::vector<${item.cpp}>`, integer: false };
    }
    case undefined:
      return { cpp: "json", integer: false }; // z.unknown()
    default:
      fail(where, `unsupported type ${s.type}`);
  }
}

function topoSort(decls: Map<string, Decl>): Decl[] {
  const done = new Set<string>();
  const out: Decl[] = [];
  const visit = (name: string, stack: string[]) => {
    if (done.has(name)) return;
    if (stack.includes(name)) fail(name, `cycle: ${[...stack, name].join(" -> ")}`);
    const d = decls.get(name);
    if (!d) fail(stack.at(-1) ?? name, `unknown type ${name}`);
    const deps = d.kind === "struct" ? d.deps : d.kind === "union" ? d.members.map((m) => m.name) : [];
    for (const dep of deps) visit(dep, [...stack, name]);
    done.add(name);
    out.push(d);
  };
  // Enums first keeps the header readable; everything else in registry order, deps first.
  for (const d of decls.values()) if (d.kind === "enum") visit(d.name, []);
  for (const name of decls.keys()) visit(name, []);
  return out;
}

function emitEnum(d: Enum, w: (l?: string) => void) {
  w(`inline const char* toString(${d.name} value) {`);
  w("    switch (value) {");
  for (const v of d.values) w(`        case ${d.name}::${pascal(v)}: return ${q(v)};`);
  w("    }");
  w('    return "?";');
  w("}");
  w();
  w(`inline std::optional<${d.name}> parse${d.name}(std::string_view text) {`);
  for (const v of d.values) w(`    if (text == ${q(v)}) return ${d.name}::${pascal(v)};`);
  w("    return std::nullopt;");
  w("}");
  w();
  w(`inline void to_json(json& j, ${d.name} value) { j = toString(value); }`);
  w();
  w(`inline void from_json(const json& j, ${d.name}& value) {`);
  w("    if (!j.is_string()) throw ParseError(\"\", \"expected a string\");");
  w(`    const auto parsed = parse${d.name}(j.get_ref<const std::string&>());`);
  w(`    if (!parsed) throw ParseError("", "unknown ${lowerFirst(d.name)} '" + j.get<std::string>() + "'");`);
  w("    value = *parsed;");
  w("}");
  w();
}

function emitStruct(d: Struct, w: (l?: string) => void) {
  const used = d.fields.length > 0 ? "" : "[[maybe_unused]] ";
  w(`inline void to_json(json& j, ${used}const ${d.name}& value) {`);
  w("    j = json::object();");
  for (const [k, v] of d.literals) w(`    j[${q(k)}] = ${q(v)};`);
  for (const f of d.fields) w(`    j[${q(f.key)}] = detail::encode(value.${f.key});`);
  w("}");
  w();
  w(`inline void from_json(const json& j, ${used}${d.name}& value) {`);
  w("    detail::expectObject(j);");
  for (const [k, v] of d.literals) w(`    detail::expectLiteral(j, ${q(k)}, ${q(v)});`);
  for (const f of d.fields) {
    w(`    detail::read(j, ${q(f.key)}, value.${f.key});`);
    if (f.min !== undefined || f.max !== undefined) {
      const lo = f.min !== undefined ? `${f.min}` : "std::nullopt";
      const hi = f.max !== undefined ? `${f.max}` : "std::nullopt";
      w(`    detail::checkRange(${q(f.key)}, value.${f.key}, ${lo}, ${hi});`);
    }
  }
  w("}");
  w();
}

// Unions get constrained templates rather than plain overloads: a to_json(json&, const Variant&)
// overload makes the compiler test every argument against std::variant's converting constructor,
// and members holding a json (ScoreHeader) send that check back into nlohmann recursively.
function unionTemplate(name: string): string {
  return `template <typename U>\n    requires std::is_same_v<U, ${name}>`;
}

function emitUnion(d: Union, w: (l?: string) => void) {
  w(unionTemplate(d.name));
  w(`void to_json(json& j, const U& value) {`);
  w("    std::visit([&j](const auto& member) { to_json(j, member); }, value);");
  w("}");
  w();
  w(unionTemplate(d.name));
  w(`void from_json(const json& j, U& value) {`);
  w(`    const std::string tag = detail::discriminator(j, ${q(d.discriminator)});`);
  for (const m of d.members) {
    w(`    if (tag == ${q(m.tag)}) {`);
    w(`        ${m.name} member;`);
    w("        from_json(j, member);");
    w("        value = std::move(member);");
    w("        return;");
    w("    }");
  }
  w(`    throw ParseError(${q(d.discriminator)}, "unknown value '" + tag + "'");`);
  w("}");
  w();
}

const PARSE_ERROR = `// Thrown by from_json on a missing key, wrong type, unknown enum value or out-of-range number.
// what() is "<path>: <reason>", e.g. "session.parts[2].density: above 1".
class ParseError : public std::runtime_error {
public:
    ParseError(std::string path, std::string reason)
        : std::runtime_error(path.empty() ? reason : path + ": " + reason),
          path_(std::move(path)),
          reason_(std::move(reason)) {}

    const std::string& path() const { return path_; }
    const std::string& reason() const { return reason_; }

    // The same error one level up: "density" inside "parts[2]" becomes "parts[2].density".
    ParseError within(const std::string& parent) const {
        if (path_.empty()) return ParseError(parent, reason_);
        return ParseError(parent + (path_[0] == '[' ? "" : ".") + path_, reason_);
    }

private:
    std::string path_;
    std::string reason_;
};
`;

const DETAIL_PRELUDE = `namespace detail {

// Declared up front so each template sees every overload (optional<vector<T>> must reach the
// vector overload, not the generic one).
template <typename T>
void decode(const json& j, T& out);
template <typename T>
void decode(const json& j, std::optional<T>& out);
template <typename T>
void decode(const json& j, std::vector<T>& out);
template <typename T>
json encode(const T& value);
template <typename T>
json encode(const std::optional<T>& value);
template <typename T>
json encode(const std::vector<T>& value);

inline void expectObject(const json& j) {
    if (!j.is_object()) throw ParseError("", "expected an object");
}

inline void decode(const json& j, std::string& out) {
    if (!j.is_string()) throw ParseError("", "expected a string");
    out = j.get<std::string>();
}

inline void decode(const json& j, bool& out) {
    if (!j.is_boolean()) throw ParseError("", "expected a boolean");
    out = j.get<bool>();
}

inline void decode(const json& j, double& out) {
    if (!j.is_number()) throw ParseError("", "expected a number");
    out = j.get<double>();
}

inline constexpr double kMaxSafeInteger = 9007199254740991.0;

inline void decode(const json& j, std::int64_t& out) {
    if (j.is_number_unsigned()) {
        if (j.get<std::uint64_t>() > static_cast<std::uint64_t>(kMaxSafeInteger)) throw ParseError("", "integer out of range");
        out = static_cast<std::int64_t>(j.get<std::uint64_t>());
        return;
    }
    if (j.is_number_integer()) {
        out = j.get<std::int64_t>();
        if (out < -static_cast<std::int64_t>(kMaxSafeInteger)) throw ParseError("", "integer out of range");
        return;
    }
    // JSON (and JavaScript) don't distinguish 3 from 3.0; accept integral floats as Zod does.
    if (j.is_number_float()) {
        const double d = j.get<double>();
        if (d >= -kMaxSafeInteger && d <= kMaxSafeInteger && d == static_cast<double>(static_cast<std::int64_t>(d))) {
            out = static_cast<std::int64_t>(d);
            return;
        }
    }
    throw ParseError("", "expected an integer");
}

inline void decode(const json& j, int& out) {
    std::int64_t wide = 0;
    decode(j, wide);
    if (wide < -2147483648LL || wide > 2147483647LL) throw ParseError("", "integer out of range");
    out = static_cast<int>(wide);
}

template <typename T>
void decode(const json& j, T& out) {
    if constexpr (std::is_same_v<T, json>)
        out = j;
    else
        from_json(j, out);
}

template <typename T>
void decode(const json& j, std::optional<T>& out) {
    if (j.is_null()) {
        out.reset();
        return;
    }
    T value{};
    decode(j, value);
    out = std::move(value);
}

template <typename T>
void decode(const json& j, std::vector<T>& out) {
    if (!j.is_array()) throw ParseError("", "expected an array");
    out.clear();
    out.reserve(j.size());
    for (std::size_t i = 0; i < j.size(); ++i) {
        T value{};
        try {
            decode(j[i], value);
        } catch (const ParseError& e) {
            throw e.within("[" + std::to_string(i) + "]");
        }
        out.push_back(std::move(value));
    }
}

template <typename T>
void read(const json& j, const char* key, T& out) {
    const auto it = j.find(key);
    if (it == j.end()) throw ParseError(key, "missing");
    try {
        decode(*it, out);
    } catch (const ParseError& e) {
        throw e.within(key);
    }
}

inline void expectLiteral(const json& j, const char* key, const char* expected) {
    const auto it = j.find(key);
    if (it == j.end()) throw ParseError(key, "missing");
    if (!it->is_string() || it->get_ref<const std::string&>() != expected)
        throw ParseError(key, std::string("expected '") + expected + "'");
}

inline std::string discriminator(const json& j, const char* key) {
    expectObject(j);
    const auto it = j.find(key);
    if (it == j.end() || !it->is_string()) throw ParseError(key, "missing");
    return it->get<std::string>();
}

template <typename T>
void checkRange(const char* key, const T& value, std::optional<double> lo, std::optional<double> hi) {
    const double v = static_cast<double>(value);
    if (lo && v < *lo) throw ParseError(key, "below " + json(*lo).dump());
    if (hi && v > *hi) throw ParseError(key, "above " + json(*hi).dump());
}

template <typename T>
void checkRange(const char* key, const std::optional<T>& value, std::optional<double> lo, std::optional<double> hi) {
    if (value) checkRange(key, *value, lo, hi);
}

// One template (no json overload): a non-template encode(const json&) would make overload
// resolution try converting every enum to json, which nlohmann can't evaluate.
template <typename T>
json encode(const T& value) {
    if constexpr (std::is_same_v<T, json>)
        return value;
    else
        return json(value);
}

template <typename T>
json encode(const std::optional<T>& value) {
    return value ? encode(*value) : json(nullptr);
}

template <typename T>
json encode(const std::vector<T>& value) {
    json array = json::array();
    for (const auto& item : value) array.push_back(encode(item));
    return array;
}

}  // namespace detail
`;
